### ISSUE TITLE
Cover more complex scenarios

### ISSUE THREAD

**Issue by shytikov** [DynamicsNinja/PCF-Prefix-Suffix-Control#2]
Hej,

Had plenty of issues when I have tried to use this control on real-life project... Recorded gif to illustrate:

![suffix](https://user-images.githubusercontent.com/1185905/68034333-c4abec80-fcc1-11e9-8a80-96192ee3c6e4.gif)

**Comment by shytikov** [comment]
Firefox.

I just looked in the code and realized that code tries to calculate text width on canvas... Which might have different implementations between Chrome and Firefox. And Edge, of course.

**Comment by shytikov** [comment]
Characters have different width and that accumulates error (open gif in new window for better view):

![chrome](https://user-images.githubusercontent.com/1185905/68048830-aa820680-fce1-11e9-95e7-344be37ab3c8.gif)

(tested in Chrome)

**Comment by DynamicsNinja** [comment]
Thanks on help. I fixed the text width calculation.
